# Generated by Django 3.1.5 on 2021-03-20 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseCode', models.CharField(max_length=12)),
                ('caseScannedDocs', models.BinaryField()),
                ('caseTitle', models.CharField(max_length=64)),
                ('caseDetails', models.TextField()),
                ('caseStatus', models.CharField(max_length=12)),
                ('caseDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialState', models.CharField(max_length=12)),
                ('healthState', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('nationalId', models.BigIntegerField()),
                ('personName', models.CharField(max_length=64)),
                ('personPhoneNum', models.CharField(max_length=12)),
                ('personAddress', models.TextField()),
                ('nationaldExpiryDate', models.DateField()),
                ('idDistrict', models.CharField(max_length=64)),
                ('scannedId', models.BinaryField()),
                ('personSalary', models.IntegerField()),
                ('personJob', models.CharField(max_length=64)),
                ('personEducationLevel', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('realName', models.CharField(max_length=64)),
                ('phoneNum', models.CharField(max_length=12)),
                ('userPassword', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobCode', models.CharField(max_length=12)),
                ('jobDate', models.DateTimeField()),
                ('jobStatus', models.CharField(max_length=12)),
                ('jobEduLevel', models.CharField(max_length=64)),
                ('jobEduMajor', models.CharField(max_length=64)),
                ('jobScannedDocs', models.BinaryField()),
                ('jobCV', models.BinaryField()),
                ('JobResponsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr', to='inhouse.users')),
                ('jobPersonaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='inhouse.person')),
            ],
        ),
        migrations.CreateModel(
            name='jobComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobCommentText', models.TextField()),
                ('jobCommentDate', models.DateTimeField()),
                ('JobCommentWriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobCommentOwner', to='inhouse.users')),
                ('jobCommentCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobUpdates', to='inhouse.cases')),
            ],
        ),
        migrations.CreateModel(
            name='Families',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individualName', models.CharField(max_length=64)),
                ('individualAge', models.IntegerField()),
                ('individualJob', models.CharField(max_length=64)),
                ('individualHealthState', models.CharField(max_length=12)),
                ('individualSocialState', models.CharField(max_length=12)),
                ('individualEduLevel', models.CharField(max_length=12)),
                ('individualSalary', models.IntegerField()),
                ('personaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='inhouse.person')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingDate', models.IntegerField()),
                ('endingDate', models.IntegerField()),
                ('companyName', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('personaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='inhouse.person')),
            ],
        ),
        migrations.AddField(
            model_name='cases',
            name='casePersonaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complain', to='inhouse.person'),
        ),
        migrations.AddField(
            model_name='cases',
            name='caseResponsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='inhouse.users'),
        ),
        migrations.CreateModel(
            name='caseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseCommentText', models.TextField()),
                ('caseCommentDate', models.DateTimeField()),
                ('caseCommentCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseUpdates', to='inhouse.cases')),
                ('caseCommentWriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseCommentOwner', to='inhouse.users')),
            ],
        ),
    ]
