# Generated by Django 3.1.5 on 2021-03-22 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inhouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='scannedId',
        ),
        migrations.AlterField(
            model_name='casecomments',
            name='caseCommentWriter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caseCommentOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cases',
            name='caseResponsible',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobcomments',
            name='JobCommentWriter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobCommentOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='JobResponsible',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationaldExpiryDate',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
