# Generated by Django 3.1.5 on 2021-03-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhouse', '0004_auto_20210323_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='jobExtraDetails',
            field=models.TextField(blank=True),
        ),
    ]
