# Generated by Django 3.1.5 on 2021-03-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhouse', '0007_auto_20210324_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='caseScannedDocs',
            field=models.FileField(upload_to=''),
        ),
    ]
