# Generated by Django 3.1.5 on 2021-03-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhouse', '0009_auto_20210324_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='caseScannedDocs',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobCV',
            field=models.FileField(upload_to=''),
        ),
    ]
