# Generated by Django 3.1.5 on 2021-03-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inhouse', '0010_auto_20210324_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='families',
            name='individualRole',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
