# Generated by Django 3.1.5 on 2021-03-27 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inhouse', '0011_families_individualrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casecomments',
            old_name='caseCommentCode',
            new_name='CommentCode',
        ),
        migrations.RenameField(
            model_name='casecomments',
            old_name='caseCommentText',
            new_name='CommentText',
        ),
        migrations.RenameField(
            model_name='casecomments',
            old_name='caseCommentWriter',
            new_name='CommentWriter',
        ),
        migrations.RenameField(
            model_name='jobcomments',
            old_name='jobCommentCode',
            new_name='CommentCode',
        ),
        migrations.RenameField(
            model_name='jobcomments',
            old_name='jobCommentText',
            new_name='CommentText',
        ),
        migrations.RenameField(
            model_name='jobcomments',
            old_name='JobCommentWriter',
            new_name='CommentWriter',
        ),
        migrations.RemoveField(
            model_name='casecomments',
            name='caseCommentDate',
        ),
        migrations.RemoveField(
            model_name='jobcomments',
            name='jobCommentDate',
        ),
        migrations.AddField(
            model_name='casecomments',
            name='CommentDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcomments',
            name='CommentDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cases',
            name='caseStatus',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobStatus',
            field=models.CharField(max_length=20),
        ),
    ]
